language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
script: python setup.py test
install:
  - pip install --use-mirrors testy
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors requirements-2.5.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors requirements-2.6.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.1' ]]; then pip install --use-mirrors requirements-3.1.txt
